sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run production
branches:
  only:
    - master
